name: Jefferies Pipeline

on:
  pull_request:
    branches:
      - main

nodes:
  - name: Lint and Format
    image: rust:1.95-slim
    checkout: true
    steps:
      - rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - cargo +nightly fmt --check
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: Unit Tests
    image: rust:1.95-slim
    after: ["Lint and Format"]
    checkout: true
    env:
      ENV: TEST
    steps:
      - ls -ld app_config/config
      - ls -L app_config/config
      - pwd
      - cargo test --all-features --workspace

  - name: Build Image
    image: quay.io/podman/stable
    checkout: true
    after: ["Unit Tests"]
    steps:
      - podman build .
