name: Jefferies Pipeline

on:
  pull_request:
    branches:
      - main

nodes:
  - name: Lint and Format
    image: rust:1.95-slim
    checkout: true
    steps:
      - rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - cargo +nightly fmt --check
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: Unit Tests
    image: rust:1.95-slim
    after: ["Lint and Format"]
    checkout: true
    steps:
      - cargo test --all-features --workspace

  - name: Build Image
    image: quay.io/buildah/stable
    checkout: true
    after: ["Unit Tests"]
    env:
      HOME: /tmp
      XDG_CONFIG_HOME: /tmp/.config
    steps:
      - mkdir -p /tmp/.config/containers
      - |
        echo '[storage]
        driver = "vfs"
        runroot = "/tmp/runroot"
        graphroot = "/tmp/graphroot"
        [storage.options]
        additionalimagestores = []
        [storage.options.vfs]
        ignore_chown_errors = "true"' > /tmp/.config/containers/storage.conf

      - buildah bud --isolation chroot -f Containerfile -t jefferies:latest .
